// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY0evJ0t-Q0Lvu-g2KhDjCEqUcd7ZdOOg',
    appId: '1:301210203484:web:06e7d2d635c6542f7e3d99',
    messagingSenderId: '301210203484',
    projectId: 'todo-f32cc',
    authDomain: 'todo-f32cc.firebaseapp.com',
    storageBucket: 'todo-f32cc.appspot.com',
    measurementId: 'G-E18XR9M53M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhpA7-6PGMwpQAWGHPRS6S4-ABeMXKTWQ',
    appId: '1:301210203484:android:598f64cdd4c5cb397e3d99',
    messagingSenderId: '301210203484',
    projectId: 'todo-f32cc',
    storageBucket: 'todo-f32cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLSuuyyYFoY8ecdeuiU7Wok_XL94XFD04',
    appId: '1:301210203484:ios:6b30c53bae19238b7e3d99',
    messagingSenderId: '301210203484',
    projectId: 'todo-f32cc',
    storageBucket: 'todo-f32cc.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLSuuyyYFoY8ecdeuiU7Wok_XL94XFD04',
    appId: '1:301210203484:ios:6b30c53bae19238b7e3d99',
    messagingSenderId: '301210203484',
    projectId: 'todo-f32cc',
    storageBucket: 'todo-f32cc.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY0evJ0t-Q0Lvu-g2KhDjCEqUcd7ZdOOg',
    appId: '1:301210203484:web:f3d34f2ecf0b775d7e3d99',
    messagingSenderId: '301210203484',
    projectId: 'todo-f32cc',
    authDomain: 'todo-f32cc.firebaseapp.com',
    storageBucket: 'todo-f32cc.appspot.com',
    measurementId: 'G-537FV273P8',
  );
}
